### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by sunxia233** [dyh127/Adaptive-Exploration-for-Unsupervised-Person-Re-Identification#2]
=> Start epoch 60
Test:
Extract Features: [1/27]        Time 1.015 (1.015)      Data 0.871 (0.871)
Extract Features: [2/27]        Time 0.142 (0.579)      Data 0.000 (0.436)
Extract Features: [3/27]        Time 0.151 (0.436)      Data 0.009 (0.293)
Extract Features: [4/27]        Time 0.143 (0.363)      Data 0.000 (0.220)
Extract Features: [5/27]        Time 0.152 (0.321)      Data 0.009 (0.178)
Extract Features: [6/27]        Time 0.143 (0.291)      Data 0.000 (0.148)
Extract Features: [7/27]        Time 0.143 (0.270)      Data 0.000 (0.127)
Extract Features: [8/27]        Time 0.143 (0.254)      Data 0.000 (0.111)
Extract Features: [9/27]        Time 0.142 (0.242)      Data 0.000 (0.099)
Extract Features: [10/27]       Time 0.158 (0.233)      Data 0.009 (0.090)
Extract Features: [11/27]       Time 0.143 (0.225)      Data 0.000 (0.082)
Extract Features: [12/27]       Time 0.142 (0.218)      Data 0.000 (0.075)
Extract Features: [13/27]       Time 0.143 (0.212)      Data 0.000 (0.069)
Extract Features: [14/27]       Time 0.152 (0.208)      Data 0.009 (0.065)
Extract Features: [15/27]       Time 0.142 (0.204)      Data 0.000 (0.061)
Extract Features: [16/27]       Time 0.142 (0.200)      Data 0.000 (0.057)
Extract Features: [17/27]       Time 0.142 (0.196)      Data 0.000 (0.053)
Extract Features: [18/27]       Time 0.142 (0.193)      Data 0.000 (0.050)
Extract Features: [19/27]       Time 0.143 (0.191)      Data 0.000 (0.048)
Extract Features: [20/27]       Time 0.143 (0.188)      Data 0.000 (0.045)
Extract Features: [21/27]       Time 0.143 (0.186)      Data 0.000 (0.043)
Extract Features: [22/27]       Time 0.143 (0.184)      Data 0.000 (0.041)
Extract Features: [23/27]       Time 0.142 (0.182)      Data 0.000 (0.039)
Extract Features: [24/27]       Time 0.143 (0.181)      Data 0.000 (0.038)
Extract Features: [25/27]       Time 0.143 (0.179)      Data 0.000 (0.036)
Extract Features: [26/27]       Time 0.143 (0.178)      Data 0.000 (0.035)
Extract Features: [27/27]       Time 0.047 (0.173)      Data 0.000 (0.034)
Extract Features: [1/125]       Time 0.800 (0.800)      Data 0.655 (0.655)
Extract Features: [2/125]       Time 0.144 (0.472)      Data 0.000 (0.328)
Extract Features: [3/125]       Time 0.143 (0.362)      Data 0.000 (0.219)
Extract Features: [4/125]       Time 0.143 (0.307)      Data 0.000 (0.164)
Extract Features: [5/125]       Time 0.143 (0.274)      Data 0.000 (0.131)
Extract Features: [6/125]       Time 0.142 (0.252)      Data 0.000 (0.109)
Extract Features: [7/125]       Time 0.150 (0.238)      Data 0.008 (0.095)
Extract Features: [8/125]       Time 0.142 (0.226)      Data 0.000 (0.083)
Extract Features: [9/125]       Time 0.143 (0.217)      Data 0.000 (0.074)
Extract Features: [10/125]      Time 0.151 (0.210)      Data 0.008 (0.067)
Extract Features: [11/125]      Time 0.143 (0.204)      Data 0.000 (0.061)
Extract Features: [12/125]      Time 0.143 (0.199)      Data 0.000 (0.056)
Extract Features: [13/125]      Time 0.144 (0.195)      Data 0.000 (0.052)
Extract Features: [14/125]      Time 0.143 (0.191)      Data 0.000 (0.048)
Extract Features: [15/125]      Time 0.143 (0.188)      Data 0.000 (0.045)
Extract Features: [16/125]      Time 0.151 (0.185)      Data 0.008 (0.043)
Extract Features: [17/125]      Time 0.142 (0.183)      Data 0.000 (0.040)
Extract Features: [18/125]      Time 0.153 (0.181)      Data 0.009 (0.038)
Extract Features: [19/125]      Time 0.144 (0.179)      Data 0.000 (0.036)
Extract Features: [20/125]      Time 0.153 (0.178)      Data 0.008 (0.035)
Extract Features: [21/125]      Time 0.144 (0.176)      Data 0.000 (0.033)
Extract Features: [22/125]      Time 0.142 (0.175)      Data 0.000 (0.032)
Extract Features: [23/125]      Time 0.151 (0.174)      Data 0.009 (0.031)
Extract Features: [24/125]      Time 0.151 (0.173)      Data 0.009 (0.030)
Extract Features: [25/125]      Time 0.155 (0.172)      Data 0.011 (0.029)
Extract Features: [26/125]      Time 0.150 (0.171)      Data 0.007 (0.028)
Extract Features: [27/125]      Time 0.143 (0.170)      Data 0.000 (0.027)
Extract Features: [28/125]      Time 0.144 (0.169)      Data 0.000 (0.026)
Extract Features: [29/125]      Time 0.143 (0.168)      Data 0.000 (0.025)
Extract Features: [30/125]      Time 0.143 (0.168)      Data 0.000 (0.025)
Extract Features: [31/125]      Time 0.143 (0.167)      Data 0.000 (0.024)
Extract Features: [32/125]      Time 0.143 (0.166)      Data 0.000 (0.023)
Extract Features: [33/125]      Time 0.143 (0.165)      Data 0.000 (0.022)
Extract Features: [34/125]      Time 0.143 (0.165)      Data 0.000 (0.022)
Extract Features: [35/125]      Time 0.143 (0.164)      Data 0.000 (0.021)
Extract Features: [36/125]      Time 0.144 (0.163)      Data 0.000 (0.021)
Extract Features: [37/125]      Time 0.143 (0.163)      Data 0.000 (0.020)
Extract Features: [38/125]      Time 0.143 (0.162)      Data 0.000 (0.019)
Extract Features: [39/125]      Time 0.143 (0.162)      Data 0.000 (0.019)
Extract Features: [40/125]      Time 0.144 (0.161)      Data 0.000 (0.018)
Extract Features: [41/125]      Time 0.143 (0.161)      Data 0.000 (0.018)
Extract Features: [42/125]      Time 0.143 (0.161)      Data 0.000 (0.018)
Extract Features: [43/125]      Time 0.144 (0.160)      Data 0.000 (0.017)
Extract Features: [44/125]      Time 0.143 (0.160)      Data 0.000 (0.017)
Extract Features: [45/125]      Time 0.142 (0.159)      Data 0.000 (0.016)
Extract Features: [46/125]      Time 0.143 (0.159)      Data 0.000 (0.016)
Extract Features: [47/125]      Time 0.143 (0.159)      Data 0.000 (0.016)
Extract Features: [48/125]      Time 0.144 (0.158)      Data 0.000 (0.015)
Extract Features: [49/125]      Time 0.143 (0.158)      Data 0.000 (0.015)
Extract Features: [50/125]      Time 0.143 (0.158)      Data 0.000 (0.015)
Extract Features: [51/125]      Time 0.143 (0.157)      Data 0.000 (0.015)
Extract Features: [52/125]      Time 0.143 (0.157)      Data 0.000 (0.014)
Extract Features: [53/125]      Time 0.143 (0.157)      Data 0.000 (0.014)
Extract Features: [54/125]      Time 0.144 (0.157)      Data 0.000 (0.014)
Extract Features: [55/125]      Time 0.143 (0.156)      Data 0.000 (0.013)
Extract Features: [56/125]      Time 0.143 (0.156)      Data 0.000 (0.013)
Extract Features: [57/125]      Time 0.143 (0.156)      Data 0.000 (0.013)
Extract Features: [58/125]      Time 0.143 (0.156)      Data 0.000 (0.013)
Extract Features: [59/125]      Time 0.143 (0.156)      Data 0.000 (0.013)
Extract Features: [60/125]      Time 0.143 (0.155)      Data 0.000 (0.012)
Extract Features: [61/125]      Time 0.143 (0.155)      Data 0.000 (0.012)
Extract Features: [62/125]      Time 0.144 (0.155)      Data 0.000 (0.012)
Extract Features: [63/125]      Time 0.143 (0.155)      Data 0.000 (0.012)
Extract Features: [64/125]      Time 0.144 (0.155)      Data 0.000 (0.012)
Extract Features: [65/125]      Time 0.143 (0.154)      Data 0.000 (0.011)
Extract Features: [66/125]      Time 0.143 (0.154)      Data 0.000 (0.011)
Extract Features: [67/125]      Time 0.144 (0.154)      Data 0.000 (0.011)
Extract Features: [68/125]      Time 0.143 (0.154)      Data 0.000 (0.011)
Extract Features: [69/125]      Time 0.143 (0.154)      Data 0.000 (0.011)
Extract Features: [70/125]      Time 0.143 (0.154)      Data 0.000 (0.011)
Extract Features: [71/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [72/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [73/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [74/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [75/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [76/125]      Time 0.143 (0.153)      Data 0.000 (0.010)
Extract Features: [77/125]      Time 0.144 (0.153)      Data 0.000 (0.010)
Extract Features: [78/125]      Time 0.142 (0.153)      Data 0.000 (0.010)
Extract Features: [79/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [80/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [81/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [82/125]      Time 0.144 (0.152)      Data 0.000 (0.009)
Extract Features: [83/125]      Time 0.144 (0.152)      Data 0.000 (0.009)
Extract Features: [84/125]      Time 0.144 (0.152)      Data 0.000 (0.009)
Extract Features: [85/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [86/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [87/125]      Time 0.143 (0.152)      Data 0.000 (0.009)
Extract Features: [88/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [89/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [90/125]      Time 0.144 (0.151)      Data 0.000 (0.008)
Extract Features: [91/125]      Time 0.144 (0.151)      Data 0.000 (0.008)
Extract Features: [92/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [93/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [94/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [95/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [96/125]      Time 0.144 (0.151)      Data 0.000 (0.008)
Extract Features: [97/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [98/125]      Time 0.142 (0.151)      Data 0.000 (0.008)
Extract Features: [99/125]      Time 0.143 (0.151)      Data 0.000 (0.008)
Extract Features: [100/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [101/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [102/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [103/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [104/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [105/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [106/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [107/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [108/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [109/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [110/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [111/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [112/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [113/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [114/125]     Time 0.143 (0.150)      Data 0.000 (0.007)
Extract Features: [115/125]     Time 0.144 (0.150)      Data 0.000 (0.007)
Extract Features: [116/125]     Time 0.144 (0.150)      Data 0.000 (0.006)
Extract Features: [117/125]     Time 0.144 (0.149)      Data 0.000 (0.006)
Extract Features: [118/125]     Time 0.143 (0.149)      Data 0.000 (0.006)
Extract Features: [119/125]     Time 0.143 (0.149)      Data 0.000 (0.006)
Extract Features: [120/125]     Time 0.143 (0.149)      Data 0.000 (0.006)
Extract Features: [121/125]     Time 0.143 (0.149)      Data 0.000 (0.006)
Extract Features: [122/125]     Time 0.143 (0.149)      Data 0.000 (0.006)
Extract Features: [123/125]     Time 0.144 (0.149)      Data 0.000 (0.006)
Extract Features: [124/125]     Time 0.144 (0.149)      Data 0.000 (0.006)
Extract Features: [125/125]     Time 0.049 (0.148)      Data 0.000 (0.006)
./test.sh: line 40: 22718 Segmentation fault      (core dumped) python main.py -s ${sourceset} -t ${targetset} --resume ./checkpoint/AE_${sourceset}2${targetset}_xi_${xi}/checkpoint.pth.tar --data-dir /home/yy1048229281/data/ --evaluate

I completed the training without problems,  I completed the training without problems, but I encountered this problem when I started testing, I changed my torch version, but it still can't be solved, do you have any suggestions?
This is my current version
torch                     1.0.1                     <pip>
torchvision               0.2.2                     <pip>

**Comment by dyh127** [comment]
Well, I tried to run my code just now, including training and testing, but no error happened.
So, can you use the 'print' function to locate where the problem is?
Besides, I search the error information on the Internet, maybe this blog can helps you https://blog.csdn.net/peiyao456/article/details/70045195
